version: '3.8'

services:

  backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_URL=${DB_URL}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - db


  db:
    image: postgres:15
    container_name: financial_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=financialdb
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: