version: '3.8'

services:

  backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_URL=${DB_URL}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - ANALYSIS_SERVICE_URL=http://analysis-service:5001
    depends_on:
      - db
      - analysis-service

  analysis-service:
    build: ./analysis-service
    container_name: analysis_service
    ports:
      - "5001:5001"

  db:
    image: postgres:15
    container_name: financial_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=financialdb
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: