spring.application.name=backend

brapi.api.url=https://brapi.dev/api

# Configuração do Telegram
TELEGRAM_BOT_TOKEN=8434007320:AAEUqBco3ofaBieVUIY_PCOzhYKGqs7Q5OY
TELEGRAM_BOT_USERNAME=GabrielFinancial_Bot

# Configuração do Datasource
spring.datasource.url=jdbc:postgresql://localhost:5432/financialdb
spring.datasource.username=gabrielboliveira
spring.datasource.password=SherlockHolmes.221
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuração do JPA e Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# URL do Serviço Externo de Análise
analysis.service.url=${ANALYSIS_SERVICE_URL}
