# Nome da Aplicação
spring.application.name=backend

# URL da API Externa
brapi.api.url=https://brapi.dev/api

# Configuração do Telegram (com nomenclatura correta e usando placeholders)
telegram.bot.token=${TELEGRAM_BOT_TOKEN}
telegram.bot.username=${TELEGRAM_BOT_USERNAME}

# Configuração do Datasource (usando placeholders para todos os valores)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuração do JPA e Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# URL do Serviço Externo de Análise
analysis.service.url=${ANALYSIS_SERVICE_URL}

# Configuração do Circuit Breaker para a chamada da Brapi
resilience4j.circuitbreaker.instances.brapi.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.brapi.sliding-window-size=10
resilience4j.circuitbreaker.instances.brapi.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.brapi.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.brapi.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.brapi.automatic-transition-from-open-to-half-open-enabled=true

# Desabilitar a verificação de compatibilidade de versão do Spring Cloud
spring.cloud.compatibility-verifier.enabled=false
